// Workspace ID to name mapping and Google Sheet URLs
export interface WorkspaceData {
  id: number;
  name: string;
  google_sheet_url: string | null;
}

export const WORKSPACES: WorkspaceData[] = [
  { id: 62, name: "A1 Media", google_sheet_url: "https://docs.google.com/spreadsheets/d/1mHs9k4v8OBkGP7KQeNb_uzru85ZuNji32USMcIpNB6s/edit" },
  { id: 55, name: "AMPLIFY", google_sheet_url: "https://docs.google.com/spreadsheets/d/1c4sbDlZy7lhNP5PwgyiEYWrv-xiPHr6o9wjol0M1iEg/edit" },
  { id: 25, name: "Absolute Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1bCtvx4LlUgdjgSl9Q_wPgJD7bn97x7h7qjTnKTf8AAU/edit" },
  { id: 44, name: "Accelerate Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1vJnk1tbVbANVy9ymtvJ4C6Fg5WjRpeGlmzA7pbt0AnE/edit" },
  { id: 3, name: "Alliance Digital Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1QohXdJLMv1un311RBD3URdxb_V4vXZaTFIRgKVNYyrc/edit" },
  { id: 63, name: "Anew Media Group", google_sheet_url: "https://docs.google.com/spreadsheets/d/1nY5Pp0ccaomU3rp8XknMm12zeGbScqZcfxTsiET2swQ/edit" },
  { id: 2, name: "Avanta", google_sheet_url: null },
  { id: 30, name: "B2E Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1cBk7MfKdIQjrz6Ask3PLYNzoS82gySvWn0tG3CnMA90/edit" },
  { id: 27, name: "Back Bay Digital", google_sheet_url: "https://docs.google.com/spreadsheets/d/1uSIZbbPaFHGCy1RLsaMm-Fa6ejYGJl3tWvwBJlGvngE/edit" },
  { id: 16, name: "Beanstalk Web Solutions", google_sheet_url: "https://docs.google.com/spreadsheets/d/1gn9105tA0Zm_GD3JQuTsYZJPUJrqorAOW4HSf_hV2PM/edit" },
  { id: 40, name: "Best Local Results", google_sheet_url: "https://docs.google.com/spreadsheets/d/1sVKV8wbRfptL15tWN-o0r2XaW5MIqxlMXNHSUJM1_Z4/edit" },
  { id: 49, name: "Bowman Advertising", google_sheet_url: "https://docs.google.com/spreadsheets/d/1g0HhW495gNSUhvPUWdaSDAMpHIcJvQ07CaN3u_Gbn64/edit" },
  { id: 11, name: "Brandlift Media", google_sheet_url: "https://docs.google.com/spreadsheets/d/16tZsktLVilr38sy4hEua0U0qIlq90FDaoKRUbQOD3gE/edit" },
  { id: 14, name: "Builder", google_sheet_url: null },
  { id: 46, name: "Catalyst Growth Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1Bp1ezXERewurgJEQE1Yaqbmt04VhL66Q5IQINjGRPWc/edit" },
  { id: 17, name: "Click Giant", google_sheet_url: "https://docs.google.com/spreadsheets/d/1oiVEX3DqgvMA0ylgW5lXxmlnGd4HGYuXw_UQnXdE90Y/edit" },
  { id: 31, name: "Contractor Growth", google_sheet_url: "https://docs.google.com/spreadsheets/d/1ZZ3mYFeOUUxKdaAoUh9NTgDTOkddPzRzUMKfhcjymqM/edit" },
  { id: 35, name: "Conversion Automotive Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1PV0HJZ00HxMhxkXSJcDThpUTCx9k7VDckZW_4J-78UU/edit" },
  { id: 24, name: "Creative Grin", google_sheet_url: null },
  { id: 58, name: "Creative Studio Productions", google_sheet_url: "https://docs.google.com/spreadsheets/d/16ipjrMCf0bX6X4A8jgdFoSHz54L44BQAP-CABk0ZNz4/edit" },
  { id: 7, name: "DES Employment", google_sheet_url: "https://docs.google.com/spreadsheets/d/1YmyMcVjv8km0eAY8VgSfi4ZPvppptM-3Qty0EmX915Q/edit" },
  { id: 15, name: "DIY AI", google_sheet_url: "https://docs.google.com/spreadsheets/d/1wwNupjTkVpyrKSlxeSCVyovgcyjirrjRkM-I66DSZVA/edit" },
  { id: 10, name: "Defined Digital Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1j1uzSgutr041hlWnLvcieiMgRgwwdNpJ7k7ZFj03rTI/edit" },
  { id: 56, name: "Dekodi", google_sheet_url: null },
  { id: 43, name: "Digital 411 Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1sHAUG055y_fxYeiPoTagM84N0p82RMo9GT5KS07ZDTw/edit" },
  { id: 60, name: "Digital Horsepower", google_sheet_url: "https://docs.google.com/spreadsheets/d/1-fniekVCZOQp1W3q_vdnMArmwDv-UHPN9dW_GznBWRM/edit" },
  { id: 36, name: "Digital Renegades", google_sheet_url: null },
  { id: 19, name: "Dirigo Creative", google_sheet_url: "https://docs.google.com/spreadsheets/d/12phPmmd_jVvjXxeavTA7WqHv0gRH86brnIiE1ehy0-Y/edit" },
  { id: 39, name: "DoctoGrow", google_sheet_url: "https://docs.google.com/spreadsheets/d/10OEtURLDH_HSpu6QfbXZS_CCbOad7CfPdFB3iFWgTb4/edit" },
  { id: 6, name: "Easy Dental Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/188tCm7CSiWriMeCp6PTpHJbImsOtGVwcNdGz17dzXJc/edit" },
  { id: 9, name: "Folks Digital", google_sheet_url: "https://docs.google.com/spreadsheets/d/1LnecmtKBIB-g2go2PEw81xga3LpLMzMnsUY4iyHUFxI/edit" },
  { id: 59, name: "GIVR Media", google_sheet_url: "https://docs.google.com/spreadsheets/d/1S_dPgSPqZZ5shS03nRBHb1ZlAIQS84p8FRAhu-JHhJw/edit" },
  { id: 34, name: "Golden Girls Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1jYKa4Xg2zJD8xoOBDlOQ5rVxiLpWrtfIJ4KOlbs_GSc/edit" },
  { id: 33, name: "GreyDot Media", google_sheet_url: "https://docs.google.com/spreadsheets/d/1pkp5Aqp4KqQTzIBpecZKfB8aGE2e5dQeBIQWvG9YZl4/edit" },
  { id: 48, name: "InFocus", google_sheet_url: "https://docs.google.com/spreadsheets/d/1EG-3KnoI88aT-RpT6q9Rs94uLawwUX1K7V8lRzc31t8/edit" },
  { id: 8, name: "Inspirare Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1vWdIdU42JiS5huIa-_dtfZ8MZruDNyVGfi5PaQFeXT4/edit" },
  { id: 41, name: "Kingdon Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1OfESpUDalAgWR4PEoJUDs66NqL6YY1lPeUdVOtrfC9o/edit" },
  { id: 37, name: "Lahav Media", google_sheet_url: "https://docs.google.com/spreadsheets/d/1C7gP-ixa_RnC695PqCDcK7PFSc9qgt7UxisaVnLxqMw/edit" },
  { id: 20, name: "Leadworks", google_sheet_url: "https://docs.google.com/spreadsheets/d/1YEKz8m3MguSZWAU60EB4MpqJDpmlGv9hvIOJ_KmVWCI/edit" },
  { id: 21, name: "MacRAE", google_sheet_url: "https://docs.google.com/spreadsheets/d/1COX4nDFnrcpt6GLdCmIYK_A_PHOhHKkri__ZVqD29QE/edit" },
  { id: 29, name: "MagniTech", google_sheet_url: "https://docs.google.com/spreadsheets/d/15MpEzQOHu34cgSL4MobaKvEcPyccf9gchVSTMe29zc0/edit" },
  { id: 22, name: "Marketing Cartel", google_sheet_url: null },
  { id: 42, name: "Marketing Tenacity", google_sheet_url: "https://docs.google.com/spreadsheets/d/1GzAaKO9QS_EYlRlUjk9a6H-81OlNJBFNda2zQ80Tavg/edit" },
  { id: 53, name: "Matchbox Design Group", google_sheet_url: "https://docs.google.com/spreadsheets/d/1lu7iqmq5qcqEiVZvdVcuCKuPFIriilE8R9Y9jZvZfvM/edit" },
  { id: 28, name: "Maxify", google_sheet_url: "https://docs.google.com/spreadsheets/d/1bMEtMAShfoX1JXEchP12FDVBohUmxfe-Q9bhAeI5Vvo/edit" },
  { id: 23, name: "Medium Interactive", google_sheet_url: "https://docs.google.com/spreadsheets/d/16ADlDhs4KpFYEpfSzGWyEfDly4x_m-vYjSKxJoQ64pY/edit" },
  { id: 45, name: "Obvious Choice Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/17cVqiyO8HVPTgWrTuzw2a78C3ktGcV5y6rGlwk4fj5E/edit" },
  { id: 52, name: "PJC Media", google_sheet_url: "https://docs.google.com/spreadsheets/d/1dCVuae-9UhhIpySivkwnQ96vttha-NDEWCEdURt2EwQ/edit" },
  { id: 18, name: "Positive Growth", google_sheet_url: "https://docs.google.com/spreadsheets/d/1qmvwM-u_XPVYITYN0cFe415N5ZiUAuQdVV5Qim0aQME/edit" },
  { id: 57, name: "Practice Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1Olucj_i_4-lk4W8jf2Shd8yMv8egWKgPWTNOJkcBxz4/edit" },
  { id: 51, name: "Prime4 Digital", google_sheet_url: "https://docs.google.com/spreadsheets/d/1Mmn9kBD7Ot5Q6CL0oCz0PEud0fQGSITxyO6IIikSOlM/edit" },
  { id: 13, name: "Quist", google_sheet_url: "https://docs.google.com/spreadsheets/d/1sl-VVWDdmUNDmvDz3i_5UGpvD3TZkGLGXSsxDLqH0Sw/edit" },
  { id: 5, name: "SEO Guru", google_sheet_url: null },
  { id: 26, name: "Sequoia National", google_sheet_url: "https://docs.google.com/spreadsheets/d/15BxptyK4H4xEx_3MeHohiShc_MXDZKlD3kWuTftjsNk/edit" },
  { id: 12, name: "Sky Media Ventures", google_sheet_url: "https://docs.google.com/spreadsheets/d/1NKGq6SNmuxwizcre_ad9RweNcQXuBPzq3mzQYN4BO3o/edit" },
  { id: 50, name: "Skyport Digital", google_sheet_url: "https://docs.google.com/spreadsheets/d/11fIwjnkZvdFFHkq_NXINVdu3URk9suAY4DLxew9hdTI/edit" },
  { id: 61, name: "Social Era Marketing", google_sheet_url: "https://docs.google.com/spreadsheets/d/1lweXGCE814pbZct3rZzlxghUUoPxzLt1-K7Omj_WQuk/edit" },
  { id: 32, name: "Tech Marketing Engine", google_sheet_url: null },
  { id: 38, name: "Thynk Digital Solutions", google_sheet_url: "https://docs.google.com/spreadsheets/d/14bMtK--pbH24KEEMwze97fuA2wMiF2NXdaxPphY3kjw/edit" },
  { id: 54, name: "Unlimited Fix", google_sheet_url: "https://docs.google.com/spreadsheets/d/1o5rH-ZioWGuS6LgOOUOV83tCVwY6WtrGsh_lIfD-E_o/edit" },
  { id: 47, name: "Zafari", google_sheet_url: "https://docs.google.com/spreadsheets/d/1hRYP_0Ut9m7MjvNrwQ0s81UkYcStbXWqVc445d3oQBY/edit" },
  { id: 4, name: "iBoost Web", google_sheet_url: "https://docs.google.com/spreadsheets/d/1vWONRT6YSq8UGKTjXt0jKQQRFaPiImSX48_RmTDWxsc/edit" },
];
